Appointment/urls.py
from rest_framework import routers
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls.static import static
from django.conf import settings

from Appointment import views

router = routers.SimpleRouter(trailing_slash=False)
router.register(r'appointment', views.AppointmentViewSet, basename='appoinment')
router.register(r'classInstructor', views.ClassInstructorViewSet, basename='classInstructor')
# router.register(r'appointment-schedule', views.AppointmentScheduleViewSet,basename='appointment-schedule')
urlpatterns = [
    path('', include('InstructorDashboard.urls')),
    path('schedule', views.AppointmentScheduleViewSet.as_view(), name='schedule'),

    path('classes', views.InstructorClassGetViewSet.as_view()),
    path('booking-confirmation', views.ClassGetViewSet.as_view()),
    path('check-availablity', views.CheckAvailability.as_view()),
    path('book', views.BookInstructor.as_view()),
    path('availabilityslots', views.AvailabilitySlots.as_view()),
    path('timeslots', views.GetDateTimeSlots.as_view()),
    path('individual-slot', views.GetIndividualTimeSlots.as_view()),
    path('booking', views.BookClassInstructor.as_view(), name="booking"),
    path('instructor-available', views.CheckInstructorViewSet.as_view()),
    path('individual-booking', views.IndividualBookingViewSet.as_view()),
    path('appointment-schedule', views.AppointmentScheduleViewSet.as_view()),
    path('booking-delete', views.BookingDelete.as_view()),
    path('date-range', views.DateRange.as_view()),
]
urlpatterns += format_suffix_patterns(router.urls)
urlpatterns += static('/media', document_root=settings.MEDIA_ROOT)

InstructorDashboard/urls.py
from django.conf.urls.static import static
from django.urls import path
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns

from SharkDeck import settings
from . import views


app_name = 'InstructorDashboard'
router = routers.SimpleRouter(trailing_slash=False)
urlpatterns = [

    path('register', views.signup_view, name='register'),
    path('', views.home_view, name='home'),
    path('login', views.login_view, name='login'),
    path('logout', views.user_logout, name='user_logout'),
    path('generate-otp', views.generate_otp, name='forgot_password'),
    path('user-forget-password', views.user_pass, name='forgot_pass'),
    path('trainee/<str:trainee>', views.trainee_view, name='trainee_view'),
    path('booking/update/<int:id>', views.update_booking, name='update_appointment'),
    path('profile', views.instructor_profile, name='instructor_profile'),
    path('change/password', views.change_password, name='change_password'),
    path('profile/', views.profile_update, name='profile_update'),
    path('bookings/', views.booking_view, name='booking_view'),
    path('appointments/', views.appointment_view, name='appointment_view'),
    path('cash-transactions/', views.cash_transactions, name='cash_transactions'),
    path('update/transaction/<int:id>', views.update_transaction, name='update_transaction'),
    path('delete/transaction/<int:id>', views.delete_transaction, name='delete_transaction'),

    path('dashboard', views.dashboard_view, name='dashboard_view'),

    path('class/detail/<int:pk>', views.ClassDetailView.as_view(), name='class_detail_view'),
    path('class/list', views.class_list, name='class_list'),
    path('students/list', views.students, name='students'),
    path('class/create', views.class_create_view, name='class_create_form'),
    path('class/update/<int:id>', views.class_update_view, name='class_update_form'),
    # path('class-submit/', views.class_edit_view, name='class_edit_form'),
    path('class/delete/<int:id>', views.class_delete, name='class_delete'),

    path('page404', views.Page404, name='page404'),
    path('terms-conditions', views.terms_conditions, name='terms_conditions'),
    path('break-time', views.add_break_time, name='add_break_time'),
    path('del-time/<int:id>', views.del_break_time, name='del_break_time'),
]
urlpatterns += format_suffix_patterns(router.urls)

# handler404 = 'InstructorDashboard.views.Page404'

SharkDeck/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('instructor/', include('InstructorDashboard.urls')),
    path('', include('Appointment.urls')),
    path('user', include('user.urls')),
    path('stripe/', include('StripePayment.urls')),
    path('swim/', include('app.urls')),
    path('contact-us/', include('ContactUs.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.conf.urls.static import static
from django.urls import path

from SharkDeck import settings
from app import views

urlpatterns = [
    # path('', views.SwimTimeView),
    path('dashboard/', views.SwimTimeDashboard, name='dashboard_view'),
    path('update-profile/', views.update_profile, name='update-profile'),
    # path('dashboard/myschedule/', views.MySchedule ,name='schedule'),
    # path('dashboard/re-payment/', views.Payment,name='payment'),
    path('instructor/<str:id>', views.Registration, name='registration'),
    path('register', views.register, name="register"),
    path('logout', views.LogoutView, name="LogoutView"),
    path('delete-booking', views.DeleteBooking.as_view()),
    path('kid_delete/<int:id>', views.kid_delete, name="kid_delete"),
    path('change_kid_status/<int:id>', views.change_kid_status, name="change_kid_status"),
    path('terms_condition/', views.TermsConditionView)

    # path('register',views.Registration_view,name='registration_view'),

    # path('register', views.UserRegistrations, name="UserRegistrations"),
    # path('login', views.UserLogin, name="login"),
]

InstructorDashboard/models.py
from django.db import models

# Create your models here.

InstructorDashboard/forms.py
from django import forms
from Appointment.models import ClassInstructor
from user import models as user_model
from django.forms import modelformset_factory


class ClassCreateForm(forms.ModelForm):
    class Meta:
        model = ClassInstructor
        fields = '__all__'
        # fields = ['title', 'time_slot', 'total_days', 'description', 'price', 'thumbnail_image', 'instructor']


class ProfileImageForm(forms.Form):
    profile_img = forms.ImageField()


monday, tuesday, wednesday, thursday, friday, saturday, sunday = '1', '2', '3', '4', '5', '6', '7'


class BreakTimeForm(forms.ModelForm):
    instructor = forms.ModelChoiceField(
        queryset=user_model.Profile.objects.all(), widget=(forms.Select(attrs={
            'class': 'break_time_profile display_none',
            'type': 'text'
        })))

    class Meta:
        model = user_model.BreakTime
        fields = '__all__'
        week_name = (
            (monday, 'monday'),
            (tuesday, 'tuesday'),
            (wednesday, 'wednesday'),
            (thursday, 'thursday'),
            (friday, 'friday'),
            (saturday, 'saturday'),
            (sunday, 'sunday'),
        )
        widgets = {
            'week_day': forms.Select(choices=week_name, attrs={'class': 'form-control'}),
            'start_time': forms.TextInput(attrs={'class': 'form-control timepicker', 'placeholder': 'Start Time'}),
            'end_time': forms.TextInput(attrs={'class': 'form-control timepicker',  'placeholder': 'End Time'}),
        }


BreakTimeFormSet = modelformset_factory(user_model.BreakTime, form=BreakTimeForm, extra=1)

Appointment/views.py
import copy
import json
import logging
from datetime import datetime, timedelta
import pytz
import requests

from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet
from app.email_notification import mail_notification

from SharkDeck.constants import user_constants
from user import models as user_model
from user.decorators import authorize
from user.models import User, Kids
from .models import Appointment, ClassInstructor, BLOCKED_BY_INSTRUCTOR, BOOKED, Booking
from .serializer import BookingPostSerializer, CheckAvailabilityPostSerializer, \
    GetSlotsSerializer, AppointmentSerializer, ClassInstructorSerializer, InstructorClassGetSerializer, \
    GetDateTimeSerializer, BookClassInstructorSerializer, ClassGetSerializer, CheckInstructorAvailableSerializer, \
    IndividualTimeSlotsSerializer, IndividualBookingSerializer, AppointmentScheduleSerializer, GetAppointmentSerializer
from StripePayment.serializers import RepaymentBookingSeralizer
from Appointment import models as appointment_model

# Get an instance of a logger
logger = logging.getLogger(__name__)


class ClassInstructorViewSet(ModelViewSet):
    serializer_class = ClassInstructorSerializer
    permission_classes = (IsAuthenticated,)
    queryset = ClassInstructor.objects.all()

    @authorize([user_constants.Instructor, user_constants.Trainee])
    def get_queryset(self):
        if self.user.user_type == user_constants.Trainee:
            return ClassInstructor.objects.all()
        else:
            return ClassInstructor.objects.filter(instructor=self.user)

    @authorize([user_constants.Instructor])
    def create(self, request, *args, **kwargs):
        serializer = ClassInstructorSerializer(data=request.data, context={'user': request.user})
        if serializer.is_valid():
            serializer.validated_data['instructor'] = request.user
            serializer.save()
            logger.info(
                f"Instructor '{request.user}' created Class '{serializer.validated_data['title']}' successfully")
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            logger.warning(f"Instructor '{request.user}' Failed to create a Class due to {serializer.errors}")
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ClassGetViewSet(APIView):
    @authorize([user_constants.Trainee])
    def get(self, request):
        try:
            parm = int(self.query_params.get('id'))
        except:
            logger.warning(f"{request.user} want to get class Invalid ID='{self.query_params.get('id')}'.")
            return Response({'error': 'Invalid Class ID.'}, status=status.HTTP_400_BAD_REQUEST)
        try:
            class_instructor = ClassInstructor.objects.get(id=parm)
        except ClassInstructor.DoesNotExist:
            logger.warning(f"Class with this ID='{self.query_params.get('id')}' Does Not Exist.")
            return Response({'error': 'Class Not Found.'})
        serializer = ClassGetSerializer(class_instructor, many=False, context={"request": request})
        if serializer.data:
            return Response(serializer.data, status=status.HTTP_200_OK)
        logger.warning(f"Getting Classes Failed due to {serializer.errors}")
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class InstructorClassGetViewSet(APIView):
    @authorize([user_constants.Trainee])
    def get(self, request):
        try:
            parm = int(self.query_params.get('id'))
        except ValueError:
            logger.warning(f"Instructor ID must be Integer, You entered Invalid ID = '{self.query_params.get('id')}'")
            return Response({'error': 'Instructor ID must be an Integer'}, status=status.HTTP_400_BAD_REQUEST)

        class_instructor = ClassInstructor.objects.filter(instructor_id=parm).order_by('-id')
        serializer = InstructorClassGetSerializer(class_instructor, many=True, context={"request": request})
        if serializer.data:
            return Response(serializer.data, status=status.HTTP_200_OK)
        else:
            logger.info(f"{class_instructor.iterator} have not created any class yet.")
            return Response({'no_data': f'Instructor = {class_instructor.iterator} does not have any class yet.'},
                            status=status.HTTP_204_NO_CONTENT)


class AppointmentViewSet(ModelViewSet):
    serializer_class = AppointmentSerializer
    permission_classes = (IsAuthenticated,)
    queryset = Appointment.objects.all()

    def dispatch(self, request, *args, **kwargs):
        dispatch = super().dispatch(request, *args, **kwargs)
        if not self.request.user or self.request.user.is_anonymous:
            logger.error(f"User is not Authorized")
            return JsonResponse({'error': 'user is not Authorized'}, status=status.HTTP_403_FORBIDDEN)
        if not (self.request.user.user_type == user_constants.Trainee):
            logger.error(f"{self.request.user} is not Trainee")
            return JsonResponse({'error': 'user is not Trainee'}, status=status.HTTP_400_BAD_REQUEST)
        return dispatch


def check_availability(start_time, instructor, avoid_blocked_time=False):
    if not start_time.tzinfo:
        start_time = start_time
    appointments = Appointment.objects.filter(start_time__date=start_time.date(),
                                              booking__class_instructor__instructor=instructor)
    is_available = True
    for appointment in appointments:
        is_available = not (appointment.start_time.replace(tzinfo=None) <= start_time.replace(tzinfo=None) <= appointment.end_time.replace(tzinfo=None))
        if avoid_blocked_time and appointment.booking.booking_type == BLOCKED_BY_INSTRUCTOR:
            return True, False
        if not is_available:
            break
    if avoid_blocked_time:
        return is_available, True
    return is_available


class CheckAvailability(APIView):
    def post(self, request):
        ser = CheckAvailabilityPostSerializer(data=request.data)
        ser.is_valid(raise_exception=True)
        try:
            class_instructor = ClassInstructor.objects.get(instructor=ser.validated_data['instructor'],
                                                           id=ser.validated_data['class_instructor'].id)
        except ClassInstructor.DoesNotExist:
            return Response({'error': "Instructor Does not Exists. "}, status=status.HTTP_400_BAD_REQUEST)
        time_slot = class_instructor.time_slot
        should_book = ser.validated_data.get('should_book')
        booked_time = {}
        is_available = True
        start_date_temp = ser.validated_data['start_datetime']
        end_date_raw = start_date_temp + timedelta(days=class_instructor.total_days)
        while start_date_temp < end_date_raw:
            is_available, should_increment = check_availability(
                start_date_temp, ser.validated_data['instructor'],
                avoid_blocked_time=True)
            if not is_available:
                return Response({'is_available': False})
            if should_increment:
                if should_book:
                    is_available = False
                    Appointment.objects.create(start_time=start_date_temp,
                                               end_time=start_date_temp + timedelta(minutes=time_slot),
                                               class_instructor=class_instructor,
                                               booking_type=BOOKED)
                booked_time[str(start_date_temp.date())] = [start_date_temp.time(),
                                                            (start_date_temp + timedelta(minutes=time_slot)).time()]
                start_date_temp += timedelta(days=1)
            else:
                start_date_temp += timedelta(days=1)
                end_date_raw += timedelta(days=1)
        return Response({'is_available': is_available,
                         'start_date_temp': ser.validated_data['start_datetime'],
                         'end_date_raw': end_date_raw,
                         'booked': booked_time})


class BookInstructor(APIView):

    @authorize([user_constants.Trainee])
    def get(self, request):
        ser = BookingPostSerializer(data=request.data)
        ser.is_valid(raise_exception=True)
        try:
            class_instructor = ClassInstructor.objects.get(id=ser.validated_data['class_instructor'].id,
                                                           instructor=ser.validated_data['instructor'])
        except ClassInstructor.DoesNotExist:
            logger.warning(f"Class not found with this ID = {ser.validated_data['class_instructor'].id}.")
            return Response({"error": "Class not found."}, status=status.HTTP_400_BAD_REQUEST)
        time_slot = class_instructor.time_slot
        is_available = check_availability(
            ser.validated_data['start_time'], ser.validated_data['instructor'])
        if is_available:
            Appointment.objects.create(start_time=ser.validated_data['start_time'],
                                       end_time=ser.validated_data['start_time'] + timedelta(minutes=time_slot),
                                       class_instructor=class_instructor,
                                       booking_type=BOOKED, booked_by=request.user)

            return Response({'is_available': is_available, 'booked': True})

        return Response({'is_available': is_available})


def get_timeslots(slot, date, instructor):
    raw_date = datetime(date.year, date.month, date.day)
    processing_date = datetime(date.year, date.month, date.day)
    date_range = {}
    while processing_date.date() == raw_date.date():

templates/InstructorDashboard/class-list.html
{% extends 'InstructorDashboard/base/base.html' %}
{% block title_block %}Swim Time Instructor{% endblock %}
{% block page_content %}


    <div class="page-content">
        <div class="container-fluid">
                 <div class="nav-link">
                     <a class=" btn btn-sm btn-soft-info" href="{% url 'InstructorDashboard:class_create_form' %}" role="button"><i class="fas fa-plus mr-2"></i>New Class</a>
                    <div class="row">
                        {% if classes %}
                            {% for class in classes %}
                                <div class="col-md-6">
                                    <div class="card" style="margin-bottom:10px;">
                                        <div class="card-body">
                                            <div class="row ">
                                                <div class="col-auto">
                                                    <img src="{{ class.thumbnail_image.url }}" alt="user" width="250px" height="150px" class="align-self-center mb-3 mb-lg-0">
                                                </div><!--end col-->
                                                <div class="col align-self-center">
                                                    <p class="font-18 font-weight-semibold mb-2">{{ class.title }}</p>
                                                    <p class="text">{{ class.description | truncatechars:35 }}</p>
                                                    <ul type="square">
                                                        <li>{{ class.time_slot }} Min/Day</li><li>{{ class.total_days }} Days</li>
                                                        <li>${{ class.price }}</li>
                                                    </ul>
                                                    <a href="{% url 'InstructorDashboard:class_delete' class.id %}" id="mySmallModalLabel" class="btn btn-soft-danger btn-sm" data-toggle="modal"data-target="#exampleModalSmall">Delete</a>
                                                    <a href="{% url 'InstructorDashboard:class_update_form' class.id %}" class="btn btn-soft-primary btn-sm">Edit</a>
                                                    <a href="{% url 'InstructorDashboard:class_detail_view' class.id %}" class="btn btn-soft-info btn-sm" >View</a>
                                                </div><!--end col-->
                                            </div> <!--end row-->
                                        </div><!--end card-body-->
                                    </div><!--end card-->
                                </div><!--end col-->



                                    <div class="modal fade bd-example-modal-sm" id="exampleModalSmall" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                                        <div class="modal-dialog modal-sm" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h6 class="modal-title m-0" id="mySmallModalLabel">Delete Confirm!</h6>
                                                    <button type="button" class="close " data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true"><i class="la la-times"></i></span>
                                                    </button>
                                                </div>
                                                <div class="modal-body text-center">
                                                    <img src="{{ class.thumbnail_image.url}}" alt="" class="thumb-lg rounded-circle">
                                                    <h4 class="mb-1">{{ class.title }}</h4>
                                                    <p class="mb-0" style="color: #7f1a30">Do You want to Delete it?</p>
                                                </div><!--end modal-body-->
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary btn-xs " data-dismiss="modal">Close</button>
                                                <a href="{% url 'InstructorDashboard:class_delete' class.id %}" ><button type="button" class="btn btn-gradient-danger btn-xs" >Delete</button></a>
                                                </div><!--end modal-footer-->
                                            </div><!--end modal-content-->
                                        </div><!--end modal-dialog-->
                                    </div><!--end modal-->
                            {% endfor %}
                        {% endif %}
                    </div>
                 </div>
        </div>
    </div>


{% endblock %}

templates/InstructorDashboard/classinstructor_confirm_delete.html
<form method="post">
{{ form }}
    {% csrf_token %}

    Do you want to delete class?

    <button type="submit">Delete</button>

    <a href="/instructor/class-list">Cancel</a>

</form>

templates/InstructorDashboard/students.html
{% extends 'InstructorDashboard/base/base.html' %}
{% block title_block %}Swim Time Instructor{% endblock %}
{% load static %}
{% block exttra_style %}
    <!-- DataTables -->
    <link href="{% static 'css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block page_content %}
    <div class="page-content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    {#            {% if stripe_msg %}#}
                    {##}
                    {#                        {% else %}#}
                    {#                        <div class="col-md-12">#}
                    {#                            <p class="alert pt-4 mt-3 pb-4 bg-danger-50 font-15 text-white" style="color: white !important;">Connect your <strong>stripe account</strong> to start receiving payments directly. Otherwise Swim Time Solutions will receive payment on your behalf &amp; process you manually later.</p>#}
                    {#                        </div>#}
                    {#                    {% endif %}#}
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Your Students</h4>
                            <p class="text-muted mb-0">A list of all the Students who are taking classes from you.
                            </p>
                        </div><!--end card-header-->
                        <div class="card-body">
                            <div id="datatable_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <table
                                                class="table dataTable table-bordered dt-responsive nowrap dataTable no-footer dtr-inline"
                                                style="border-collapse: collapse; border-spacing: 0px; width: 100%;"
                                                role="grid" aria-describedby="datatable_info">
                                            <thead>
                                            <tr role="row">
                                                <th class="sorting_asc" tabindex="0" aria-controls="datatable"
                                                    rowspan="1" colspan="1" style="width: 150.8px;"
                                                    aria-sort="ascending"
                                                    aria-label="Name: activate to sort column descending">Student Name
                                                </th>
                                                <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1"
                                                    colspan="1" style="width: 150.8px;"
                                                    aria-label="Position: activate to sort column ascending">Guardian
                                                    Name
                                                </th>
                                                <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1"
                                                    colspan="1" style="width: 150.8px;"
                                                    aria-label="Position: activate to sort column ascending">Guardian-2
                                                    Name
                                                </th>
                                                <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1"
                                                    colspan="1"
                                                    aria-label="Age: activate to sort column ascending">Date of Birth
                                                </th>
                                                <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1"
                                                    colspan="1"
                                                    aria-label="Age: activate to sort column ascending">Age
                                                </th>
                                                <th class="sorting_asc" tabindex="0" aria-controls="datatable"
                                                    rowspan="1" colspan="1" style="width: 150.8px;"
                                                    aria-sort="ascending"
                                                    aria-label="Name: activate to sort column descending">Email
                                                </th>
                                                <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1"
                                                    colspan="1" style="width: 118.8px;"
                                                    aria-label="Start date: activate to sort column ascending">
                                                    Mobile Number
                                                </th>
                                                <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1"
                                                    colspan="1" style="width: 118.8px;"
                                                    aria-label="Start date: activate to sort column ascending">
                                                    Bookings
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody>

                                            {% for student in students %}


                                                <tr>
                                                    <td>
                                                        <b>
                                                            <a href="{% url 'InstructorDashboard:trainee_view'  student.id %}"
                                                               class="text-primary">
                                                                {{ student.kids_name }}
                                                            </a>
                                                        </b>
                                                    </td>

                                                    <td>{{ student.parent.first_name }} {{ student.parent.last_name }}</td>
                                                    <td>{{ student.parent.father_name }}</td>
                                                    <td>{{ student.date_of_birth|date:"m/d/Y" }}</td>
                                                    {% for key, value in ages.items %}
                                                        {% if key == student.id %}
                                                            <td>{{ value }}</td>
                                                        {% endif %}
                                                    {% endfor %}
                                                    <td> {{ student.parent.email }}</td>

                                                    <td>{{ student.parent.mobile_no }}</td>

                                                    <td>
                                                        {% if student.kids_name in booking_count %}
                                                            {% for key, value in booking_count.items %}
                                                                {% if student.kids_name == key %}
                                                                    {{ value }}
                                                                {% endif %}
                                                            {% endfor %}
                                                        {% else %}
                                                            0
                                                        {% endif %}
                                                    </td>

                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_script %}
    <!-- Required datatable js -->
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            $(".dataTable").DataTable()
        });

    </script>


{% endblock %}