InstructorDashboard/urls.py
from django.conf.urls.static import static
from django.urls import path
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns

from SharkDeck import settings
from . import views


app_name = 'InstructorDashboard'
router = routers.SimpleRouter(trailing_slash=False)
urlpatterns = [

    path('register', views.signup_view, name='register'),
    path('', views.home_view, name='home'),
    path('login', views.login_view, name='login'),
    path('logout', views.user_logout, name='user_logout'),
    path('generate-otp', views.generate_otp, name='forgot_password'),
    path('user-forget-password', views.user_pass, name='forgot_pass'),
    path('trainee/<str:trainee>', views.trainee_view, name='trainee_view'),
    path('booking/update/<int:id>', views.update_booking, name='update_appointment'),
    path('profile', views.instructor_profile, name='instructor_profile'),
    path('change/password', views.change_password, name='change_password'),
    path('profile/', views.profile_update, name='profile_update'),
    path('bookings/', views.booking_view, name='booking_view'),
    path('appointments/', views.appointment_view, name='appointment_view'),
    path('cash-transactions/', views.cash_transactions, name='cash_transactions'),
    path('update/transaction/<int:id>', views.update_transaction, name='update_transaction'),
    path('delete/transaction/<int:id>', views.delete_transaction, name='delete_transaction'),

    path('dashboard', views.dashboard_view, name='dashboard_view'),

    path('class/detail/<int:pk>', views.ClassDetailView.as_view(), name='class_detail_view'),
    path('class/list', views.class_list, name='class_list'),
    path('students/list', views.students, name='students'),
    path('class/create', views.class_create_view, name='class_create_form'),
    path('class/update/<int:id>', views.class_update_view, name='class_update_form'),
    # path('class-submit/', views.class_edit_view, name='class_edit_form'),
    path('class/delete/<int:id>', views.class_delete, name='class_delete'),

    path('page404', views.Page404, name='page404'),
    path('terms-conditions', views.terms_conditions, name='terms_conditions'),
    path('break-time', views.add_break_time, name='add_break_time'),
    path('del-time/<int:id>', views.del_break_time, name='del_break_time'),
]
urlpatterns += format_suffix_patterns(router.urls)

# handler404 = 'InstructorDashboard.views.Page404'

SharkDeck/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('instructor/', include('InstructorDashboard.urls')),
    path('', include('Appointment.urls')),
    path('user', include('user.urls')),
    path('stripe/', include('StripePayment.urls')),
    path('swim/', include('app.urls')),
    path('contact-us/', include('ContactUs.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.conf.urls.static import static
from django.urls import path

from SharkDeck import settings
from app import views

urlpatterns = [
    # path('', views.SwimTimeView),
    path('dashboard/', views.SwimTimeDashboard, name='dashboard_view'),
    path('update-profile/', views.update_profile, name='update-profile'),
    # path('dashboard/myschedule/', views.MySchedule ,name='schedule'),
    # path('dashboard/re-payment/', views.Payment,name='payment'),
    path('instructor/<str:id>', views.Registration, name='registration'),
    path('register', views.register, name="register"),
    path('logout', views.LogoutView, name="LogoutView"),
    path('delete-booking', views.DeleteBooking.as_view()),
    path('kid_delete/<int:id>', views.kid_delete, name="kid_delete"),
    path('change_kid_status/<int:id>', views.change_kid_status, name="change_kid_status"),
    path('terms_condition/', views.TermsConditionView)

    # path('register',views.Registration_view,name='registration_view'),

    # path('register', views.UserRegistrations, name="UserRegistrations"),
    # path('login', views.UserLogin, name="login"),
]

user/urls.py
from django.conf.urls import url, include
from django.urls import path
from rest_framework import routers

from . import views

app_name = 'UserApp'
# router = routers.DefaultRouter()
router = routers.SimpleRouter(trailing_slash=False)
router.register(r'', views.UserViewSet, basename='user')
router.register(r'/profile', views.ProfileViewSet, basename='profile')
router.register(r'/student_profile', views.StudentProfileViewSet, basename='student_profile')
router.register(r'/review', views.RateReviewViewSet)
router.register(r'/generate-otp', views.OTPViewSet, basename='otp')
router.register(r'/student_update', views.StudentUpdateProfileViewset, basename='student_update')
urlpatterns = [
    path('/login', views.Authenticate.as_view(), name="api_auth"),
    path('/instructors', views.GetInstructorProfile.as_view(), name="profile"),
    path('/booked_class', views.GetBookedViewSet.as_view(), name="booked_class"),
    path('/profile_student', views.GetStudentProfileViewSet.as_view(), name="profile_student"),
    path('/request-reset-email', views.RequestPasswordResetEmail.as_view(), name="request-reset-email"),
    path('/password-reset/<uidb64>/<token>', views.PasswordTokenCheckAPI.as_view(), name='password-reset-confirm'),
    path('/password-reset-complete', views.SetNewPasswordAPIView.as_view(), name='password-reset-complete'),
    path('/reset-password', views.forgot_password, name='reset_password'),
    path('/instructor-slug', views.InstructorSlug.as_view()),
    path('/get-slug', views.InstructorGetSlug.as_view()),
    path('/profile_update', views.StudentProfileUpdateViewset.as_view(), name="update-user"),
    path('', include(router.urls))
]
urlpatterns += router.urls

templates/calander.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Static Example</title>

    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

  </head>
  <body>

    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
        <div  class="form-control datetimepicker-input" data-target="#datetimepicker1"></div>
      <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
      </div>
    </div>

    <script>
      $(function () {
        $("#datetimepicker1").datetimepicker();
      });
    </script>

  </body>
</html>

templates/forgot_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from mannatthemes.com/dastone-1/default/auth-recover-pw.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 23 Jan 2021 11:54:47 GMT -->
<head>
    <meta charset="utf-8"/>
    <title>Swim Time Instructor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description"/>
    <meta content="" name="author"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

    <!-- App favicon -->
    <link rel="shortcut icon" href="assets/images/favicon.ico">

    <!-- App css -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css"/>
    <script src={% static 'assets/js/custom.js' %}></script>
    <style>
        .top_alert_position {
            position: fixed;
            background: #fff;
            top: 10%;
            right: 30px;
            z-index: 9;
        }

        .alert .alert-close {
            display: initial !important;
        }
    </style>
</head>

<body class="account-body accountbg">
{% if error %}
    <div class="top_alert_position alert custom-alert custom-alert-danger icon-custom-alert alert-secondary-shadow fade show"
         role="alert">
        <i class="la la-skull-crossbones alert-icon text-danger align-self-center font-30 mr-3"></i>
        <div class="alert-text my-1">
            <h5 class="mb-1 font-weight-bold mt-0">Danger</h5>
            <span>{{ error }} </span>
        </div>
        <div class="alert-close ">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <strong aria-hidden="true" class="text-danger">
                    <i class="mdi mdi-close font-16"></i>
                </strong>
            </button>
        </div>
    </div>
{% endif %}
{% if success %}
    <div class="top_alert_position alert custom-alert custom-alert-success icon-custom-alert alert-secondary-shadow fade show"
         role="alert">
        <i class="mdi mdi-check-all alert-icon alert-icon text-success align-self-center font-30 mr-3"></i>
        <div class="alert-text my-1">
            <h5 class="mb-1 font-weight-bold mt-0">Success</h5>
            <span>{{ success }} </span>
        </div>
        <div class="alert-close ">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <strong aria-hidden="true" class="text-success">
                    <i class="mdi mdi-close font-16"></i>
                </strong>
            </button>
        </div>
    </div>
{% endif %}

<!-- Recover-pw page -->
<div class="container">
    <div class="row vh-100 d-flex justify-content-center">
        <div class="col-12 align-self-center">
            <div class="row">
                <div class="col-lg-5 mx-auto">
                    <div class="card">
                        <div class="card-body p-0 auth-header-box">
                            <div class="text-center p-3">
                                <a href="{% url 'InstructorDashboard:login' %}" class="logo logo-admin">
                                    <img src="{% static 'images/logo-sm-dark.png' %}" height="50" alt="logo"
                                         class="auth-logo">
                                </a>
                                <h4 class="mt-3 mb-1 font-weight-semibold text-white font-18">Reset Password For
                                    SwimTime</h4>
                                <p class="text-muted  mb-0">Enter your Email and instructions will be sent to your
                                    Email</p>
                            </div>
                        </div>
                        <div class="card-body">
                            <form class="form-horizontal auth-form" method="post"
                                  action="{% url 'UserApp:reset_password' %}">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group mb-2">
                                            <label for="username"><b>Email</b></label>
                                            <div class="input-group">
                                                <input type="email" name="email" required class="form-control"
                                                       id="email"
                                                       placeholder="Enter Email">
                                            </div>
                                        </div><!--end form-group-->
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group mb-2">
                                            <label for="otp"><b>OTP</b></label>
                                            <div class="input-group">
                                                <input type="number" name="otp" required min="0" class="form-control"
                                                       id="otp"
                                                       placeholder="Enter OTP">
                                            </div>
                                        </div><!--end form-group-->
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group mb-2">
                                            <label for="password1"><b>Enter Password</b></label>
                                            <div class="input-group">
                                                <input type="text" name="password1" required class="form-control"
                                                       id="password1"
                                                       placeholder="Enter Password">
                                            </div>
                                        </div><!--end form-group-->
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group mb-2">
                                            <label for="password2"><b>Confirm Password</b></label>
                                            <div class="input-group">
                                                <input type="text" required name="password2" class="form-control"
                                                       id="password2"
                                                       placeholder="Confirm Password">
                                            </div>
                                        </div><!--end form-group-->
                                    </div>
                                </div>

                                <div class="form-group mb-0 row">
                                    <div class="col-12 mt-2">
                                        <button class="btn btn-primary btn-block waves-effect waves-light"
                                                type="submit">Reset <i class="fas fa-sign-in-alt ml-1"></i></button>
                                    </div><!--end col-->
                                </div> <!--end form-group-->
                            </form><!--end form-->
                            <p class="text-muted mb-0 mt-3">Remember It ? <a
                                    href="{% url 'InstructorDashboard:login' %}" class="text-primary ml-2">Log in
                                here</a></p>
                        </div>
                        <div class="card-body bg-light-alt text-center">
                            <span class="text-muted d-none d-sm-inline-block">SwimTime © 2022</span>
                        </div>
                    </div><!--end card-->
                </div><!--end col-->
            </div><!--end row-->
        </div><!--end col-->
    </div><!--end row-->
</div><!--end container-->
<!-- End Recover-pw page -->


<!-- jQuery  -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/waves.js' %}"></script>
<script src="{% static 'js/feather.min.js' %}"></script>
<script src="{% static 'js/simplebar.min.js' %}"></script>


<script>
    setTimeout(function () {
        $("[data-dismiss=alert]").click();
    }, 4000);
</script>


</body>


<!-- Mirrored from mannatthemes.com/dastone-1/default/auth-recover-pw.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 23 Jan 2021 11:54:47 GMT -->
</html>

templates/message.html
{% load static %}
<link href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" rel="stylesheet" type="text/css">
{#<div style="float:right;position:fixed;width:90%;min-height:200px;z-index:2;margin-top: 70px;">#}
{#<!-- Flexbox container for aligning the toasts -->#}
{#<div aria-live="polite" id="msg" aria-atomic="true" class="d-flex justify-content-center align-items-center" style="position:relative;float:right; ">#}
{##}
{#  <!-- Then put toasts within -->#}
{#  <div class="toast {{ message.tags }}" role="alert" aria-live="assertive" aria-atomic="true" style="text-align:center;">#}
{##}
{#        <div class="toast-header" >#}
{#      <img src="{% static 'assets/img/logo2.png' %}" class="rounded mr-2" alt="..." style="width:40px;height:30px;">#}
{#      <strong class="mr-auto">Swim Time Solutions &nbsp;&nbsp; </strong>#}
{##}
{#      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">#}
{#        <span aria-hidden="true">&nbsp;&nbsp; &times; &nbsp;&nbsp;</span>#}
{#      </button>#}
{#        </div>#}
{#    <div class="toast-body" >#}
{#      {{ message }}#}
{#        <br><br>#}
{#    </div>#}
{#  </div>#}
{#</div>#}
{#</div>#}

<style>
    * {
    padding: 0;
    margin: 0;
    box-sizing: border-box;
    border: none;
    font-family: "Poppins", sans-serif;
    font-size: 14px
}
{##}
{#body {#}
{#    background-color: #f9f9f9#}
{#}#}

.wrapper {
    width: 380px;
    position: absolute;
    transform: translate(-50%, -50%);
    top: 50%;
    left: 50%
}

.toast {
    width: 100%;
    height: 80px;
    padding: 20px;
    background-color: #ffffff;
    border-radius: 7px;
    display: grid;
    grid-template-columns: 1.3fr 6fr 0.5fr;
    box-shadow: 0 15px 30px rgba(0, 0, 0, 0.08)
}

.success {
    border-left: 3px solid #47D764
}

.error {
    border-left: 3px solid #ff355b
}

.info {
    border-left: 3px solid #2F86EB
}

.warning {
    border-left: 3px solid #FFC021
}

.error i {
    color: #ff355b
}

.info i {
    color: #2F86EB
}

.warning i {
    color: #FFC021
}

.toast:not(:last-child) {
    margin-bottom: 20px
}

.outer-container,
.inner-container {
    align-self: center
}

.outer-container i {
    font-size: 35px
}

.success i {
    color: #47D764
}

.inner-container p:first-child {
    color: #101020;
    font-weight: 600;
    font-size: 16px
}

.inner-container p:last-child {
    font-size: 12px;
    font-weight: 400;
    color: #656565
}

.toast button {
    align-self: flex-start;
    background-color: transparent;
    font-size: 20px;
    color: #656565;
    line-height: 0;
    cursor: pointer;
    margin-right: -30px
}
</style>
{% for message in messages %}
 <div style="float:right;position:fixed;width:90%;min-height:20px;z-index:2;margin-top: 70px;">
<!-- Flexbox container for aligning the toasts -->
<div aria-live="polite" id="msg" aria-atomic="true" class="d-flex justify-content-center align-items-center" style="position:relative;float:right; ">

  <!-- Then put toasts within -->
  <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" style="text-align: center;">

        <div class="toast-header" >
      <img src="{% static 'assets/img/logo2.png' %}" class="rounded mr-2" alt="..." style="width:60px;height:50px;margin-top:-7px;">



      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true"></span>
      </button>
        </div>
    <div class="toast-body" style="margin-top:10px;color:black;">

      {{ message }}

    </div>
  </div>
</div>
</div>

{% endfor %}

  <script type="text/javascript">
setTimeout(function (){
       if ($('#msg').length>0){
           $('#msg').remove();
       }
   }, 5000)

{#setTimeout(function () {#}
{#            $('[role="alert"]').click();#}
{#        }, 5000);#}
    </script>

templates/my_shedule.html
{% extends 'base.html' %}
{% load static %}

{% block sidebar_content %}

    <a _ngcontent-nwk-c28="" href={% url 'dashboard_view' %} class="">
        <div _ngcontent-nwk-c28="" class="tab-link first">
            <div _ngcontent-nwk-c28="" class="img-div img-div-one"></div>
            <h3 _ngcontent-nwk-c28="">INSTRUCTOR</h3></div>
    </a>
    <a _ngcontent-nwk-c28="" href={% url 'schedule' %} class="active">
        <div _ngcontent-nwk-c28="" class="tab-link">
            <div _ngcontent-nwk-c28="" class="img-div img-div-two"></div>
            <h3 _ngcontent-nwk-c28="">MY SCHEDULE</h3></div>
    </a>
    <a _ngcontent-nwk-c28="" href={% url 'repayment_classes' %} class="">
        <div _ngcontent-nwk-c28="" class="tab-link">
            <div _ngcontent-nwk-c28="" class="img-div img-div-four"></div>
            <h3 _ngcontent-nwk-c28="">PAYMENT</h3></div>
    </a>
{% endblock %}

{% block page_content %}

    <div _ngcontent-uss-c31="" class="col-md-11 content">
        <div _ngcontent-uss-c31="" class="main-content">
            <div _ngcontent-uss-c31="" class="container">
                <div _ngcontent-uss-c31="" class="main_container">
                    <div _ngcontent-uss-c31="" class="row">
                        <div _ngcontent-uss-c31="" class="col-md-12"></div>
                        <div _ngcontent-uss-c31="" class="col-md-12">


                            <div _ngcontent-uss-c31="" class="col-md-6 left-in head">
                                <div _ngcontent-uss-c31="" class="session_heading"><h3 _ngcontent-uss-c31="">PREVIOUS
                                    SESSION</h3></div>
                                <div _ngcontent-uss-c31="" class="ScrollView">
                                    {% if prev_session  %}<!---->
                                        {% for data in prev_session %}
                                            <div _ngcontent-uss-c31="">

                                                <div _ngcontent-uss-c31="" class="appointment-div"
                                                     style="">

                                                    <div _ngcontent-uss-c31="" class="block">
                                                        <div _ngcontent-uss-c31="" class="top-block"><p
                                                                _ngcontent-uss-c31=""
                                                                class="classTitle"><span
                                                                _ngcontent-uss-c31="">{{ data.title }}</span>
                                                            <!----></p><h4
                                                                _ngcontent-uss-c31="">{{ data.start_time }}</h4>
                                                            <!----><p _ngcontent-uss-c31="">{{ data.kid_name }} appointment had
                                                                completed {{ data.instructor }}</p><!----></div>
                                                        <div _ngcontent-uss-c31="" class="bottom-div">
                                                            <div _ngcontent-uss-c31="" class="row">
                                                                <div _ngcontent-uss-c31=""
                                                                     class="col-md-4 ImageContent"><img
                                                                        _ngcontent-uss-c31="" alt="instructor image"
                                                                        src="{{ data.profile_img }}">
                                                                </div>
                                                                <div _ngcontent-uss-c31=""
                                                                     class="col-md-8 bottom-div-right"><h3
                                                                        _ngcontent-uss-c31="">{{ data.instructor }}</h3>
                                                                    <p _ngcontent-uss-c31=""><i _ngcontent-uss-c31=""
                                                                                                class="fa fa-map-marker"></i>{{ data.address }}
                                                                    </p><!----><p _ngcontent-uss-c31=""><i
                                                                            _ngcontent-uss-c31=""
                                                                            class="fa fa-phone"></i>{{ data.mobile_no }}
                                                                    </p><!----></div>
                                                            </div>
                                                        </div>
                                                    </div><!----></div>
                                                <!----></div>



                                        {% endfor %}
                                    {% else %}
                                        <div _ngcontent-xmu-c31="" class="col-md-12">
                                            <div _ngcontent-xmu-c31="" class="alert alert-info"><h1
                                                    _ngcontent-xmu-c31="" class="text-center">There is no previous
                                                appointment.</h1><br></div><br>
                                        </div>
                                    {% endif %}

                                    <!----></div><!----></div>


                            <div _ngcontent-uss-c31="" class="col-md-6 right-in head">
                                <div _ngcontent-uss-c31="" class="session_heading"><h3 _ngcontent-uss-c31="">NEXT
                                    SESSION</h3></div>
                                <div _ngcontent-uss-c31="" class="ScrollView">
                                    {% if next_session %}
                                        {%  for data in next_session %}<!---->
                                            {% if data.status == '1' %}
                                            <div _ngcontent-uss-c31="" class="appointment-div "
                                                 >
                                                <div _ngcontent-uss-c31="" class="block">
                                                    <div _ngcontent-uss-c31="" class="top-block"><p
                                                            _ngcontent-uss-c31=""
                                                            class="classTitle"><span
                                                            _ngcontent-uss-c31="">{{ data.title }} class</span><!---->
                                                    </p><h4
                                                            _ngcontent-uss-c31="">{{ data.start_time }}</h4>
                                                        <!----><p _ngcontent-uss-c31=""> {{ data.kid_name }} has an appointment
                                                            with {{ data.instructor }}</p><!----></div>
                                                    <div _ngcontent-uss-c31="" class="bottom-div">
                                                        <div _ngcontent-uss-c31="" class="row">
                                                            <div _ngcontent-uss-c31="" class="col-md-4 ImageContent">
                                                                <img
                                                                        _ngcontent-uss-c31="" alt="instructor image"
                                                                        src="{{ data.profile_img }}">
                                                            </div>
                                                            <div _ngcontent-uss-c31=""
                                                                 class="col-md-8 bottom-div-right"><h3
                                                                    _ngcontent-uss-c31="">{{ data.instructor }}</h3>
                                                                <p _ngcontent-uss-c31=""><i _ngcontent-uss-c31=""
                                                                                            class="fa fa-map-marker"></i> {{ data.address }}
                                                                </p><!----><p _ngcontent-uss-c31=""><i
                                                                        _ngcontent-uss-c31=""
                                                                        class="fa fa-phone"></i>{{ data.mobile_no }}
                                                                </p><!----></div>
                                                        </div>
                                                    </div>

                                                </div>

                                            </div>
                                            {% endif %}
                                        {% endfor %}
                                    {% else %}
                                        <div _ngcontent-xmu-c31="" class="col-md-12"><div _ngcontent-xmu-c31="" class="alert alert-info"><h1 _ngcontent-xmu-c31="" class="text-center">There is no next scheduled appointment.</h1></div><br></div>
                                    {% endif %}
                                    <!----></div><!----></div>


                        </div><!---->
                        <ngx-spinner _ngcontent-uss-c31="" bdcolor="rgba(50, 50, 50, 0.8)" size="default"
                                     type="ball-spin-clockwise" _nghost-uss-c29=""><!----></ngx-spinner><!----></div>
                </div>
            </div>
        </div>
    </div>

    <script>

    </script>

{% endblock %}