InstructorDashboard/urls.py
from django.conf.urls.static import static
from django.urls import path
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns

from SharkDeck import settings
from . import views


app_name = 'InstructorDashboard'
router = routers.SimpleRouter(trailing_slash=False)
urlpatterns = [

    path('register', views.signup_view, name='register'),
    path('', views.home_view, name='home'),
    path('login', views.login_view, name='login'),
    path('logout', views.user_logout, name='user_logout'),
    path('generate-otp', views.generate_otp, name='forgot_password'),
    path('user-forget-password', views.user_pass, name='forgot_pass'),
    path('trainee/<str:trainee>', views.trainee_view, name='trainee_view'),
    path('booking/update/<int:id>', views.update_booking, name='update_appointment'),
    path('profile', views.instructor_profile, name='instructor_profile'),
    path('change/password', views.change_password, name='change_password'),
    path('profile/', views.profile_update, name='profile_update'),
    path('bookings/', views.booking_view, name='booking_view'),
    path('appointments/', views.appointment_view, name='appointment_view'),
    path('cash-transactions/', views.cash_transactions, name='cash_transactions'),
    path('update/transaction/<int:id>', views.update_transaction, name='update_transaction'),
    path('delete/transaction/<int:id>', views.delete_transaction, name='delete_transaction'),

    path('dashboard', views.dashboard_view, name='dashboard_view'),

    path('class/detail/<int:pk>', views.ClassDetailView.as_view(), name='class_detail_view'),
    path('class/list', views.class_list, name='class_list'),
    path('students/list', views.students, name='students'),
    path('class/create', views.class_create_view, name='class_create_form'),
    path('class/update/<int:id>', views.class_update_view, name='class_update_form'),
    # path('class-submit/', views.class_edit_view, name='class_edit_form'),
    path('class/delete/<int:id>', views.class_delete, name='class_delete'),

    path('page404', views.Page404, name='page404'),
    path('terms-conditions', views.terms_conditions, name='terms_conditions'),
    path('break-time', views.add_break_time, name='add_break_time'),
    path('del-time/<int:id>', views.del_break_time, name='del_break_time'),
]
urlpatterns += format_suffix_patterns(router.urls)

# handler404 = 'InstructorDashboard.views.Page404'

SharkDeck/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('instructor/', include('InstructorDashboard.urls')),
    path('', include('Appointment.urls')),
    path('user', include('user.urls')),
    path('stripe/', include('StripePayment.urls')),
    path('swim/', include('app.urls')),
    path('contact-us/', include('ContactUs.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.conf.urls.static import static
from django.urls import path

from SharkDeck import settings
from app import views

urlpatterns = [
    # path('', views.SwimTimeView),
    path('dashboard/', views.SwimTimeDashboard, name='dashboard_view'),
    path('update-profile/', views.update_profile, name='update-profile'),
    # path('dashboard/myschedule/', views.MySchedule ,name='schedule'),
    # path('dashboard/re-payment/', views.Payment,name='payment'),
    path('instructor/<str:id>', views.Registration, name='registration'),
    path('register', views.register, name="register"),
    path('logout', views.LogoutView, name="LogoutView"),
    path('delete-booking', views.DeleteBooking.as_view()),
    path('kid_delete/<int:id>', views.kid_delete, name="kid_delete"),
    path('change_kid_status/<int:id>', views.change_kid_status, name="change_kid_status"),
    path('terms_condition/', views.TermsConditionView)

    # path('register',views.Registration_view,name='registration_view'),

    # path('register', views.UserRegistrations, name="UserRegistrations"),
    # path('login', views.UserLogin, name="login"),
]

InstructorDashboard/models.py
from django.db import models

# Create your models here.

InstructorDashboard/forms.py
from django import forms
from Appointment.models import ClassInstructor
from user import models as user_model
from django.forms import modelformset_factory


class ClassCreateForm(forms.ModelForm):
    class Meta:
        model = ClassInstructor
        fields = '__all__'
        # fields = ['title', 'time_slot', 'total_days', 'description', 'price', 'thumbnail_image', 'instructor']


class ProfileImageForm(forms.Form):
    profile_img = forms.ImageField()


monday, tuesday, wednesday, thursday, friday, saturday, sunday = '1', '2', '3', '4', '5', '6', '7'


class BreakTimeForm(forms.ModelForm):
    instructor = forms.ModelChoiceField(
        queryset=user_model.Profile.objects.all(), widget=(forms.Select(attrs={
            'class': 'break_time_profile display_none',
            'type': 'text'
        })))

    class Meta:
        model = user_model.BreakTime
        fields = '__all__'
        week_name = (
            (monday, 'monday'),
            (tuesday, 'tuesday'),
            (wednesday, 'wednesday'),
            (thursday, 'thursday'),
            (friday, 'friday'),
            (saturday, 'saturday'),
            (sunday, 'sunday'),
        )
        widgets = {
            'week_day': forms.Select(choices=week_name, attrs={'class': 'form-control'}),
            'start_time': forms.TextInput(attrs={'class': 'form-control timepicker', 'placeholder': 'Start Time'}),
            'end_time': forms.TextInput(attrs={'class': 'form-control timepicker',  'placeholder': 'End Time'}),
        }


BreakTimeFormSet = modelformset_factory(user_model.BreakTime, form=BreakTimeForm, extra=1)

InstructorDashboard/views.py
import collections
import logging
import os
import urllib.request
from urllib import request
from datetime import datetime, timedelta, date
from random import randint

import pytz
import requests
import urllib3
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import DetailView
from icalendar import Calendar, Event, vCalAddress, vText
from datetime import datetime
from pathlib import Path

from Appointment import models as appointment_model
from Appointment import utilities
from Appointment.models import ClassInstructor, APPOINTMENT_STATUS, Appointment
from SharkDeck.constants import user_constants
from StripePayment.models import StripeAccount
from app.email_notification import mail_notification
from user import models as user_models
from user.models import User, Kids
from user.email_services import sent_mail
from user.models import Profile, User
from . import seializer
from . import serializer, utility
from .forms import BreakTimeFormSet
from SharkDeck import settings
from SharkDeck.tasks import sent_mail_task

BASE_URL = settings.BASE_URL

logger = logging.getLogger(__name__)


def generate_slug(first_name, last_name):
    obj = len(user_models.Profile.objects.all())
    if user_models.Profile.objects.filter(slug=first_name).exists():
        if user_models.Profile.objects.filter(slug=first_name + last_name).exists():
            slug = (first_name + last_name + str(obj))
            return slug
        else:
            slug = (first_name + last_name)
            return slug
    else:
        slug = first_name
        return slug


def signup_view(request):
    if request.user.is_authenticated:
        return redirect('InstructorDashboard:dashboard_view')

    context = {}
    if request.method == 'GET':
        return render(request, 'InstructorDashboard/auth/login.html')

    else:
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        conf_password = request.POST.get('conf_password')
        mobile_no = request.POST.get('mobile_no')
        if user_models.User.objects.filter(email=email).exists():
            return render(request, 'InstructorDashboard/auth/login.html', {'error': 'email already exist.'})
        if user_models.User.objects.filter(mobile_no=mobile_no).exists():
            return render(request, 'InstructorDashboard/auth/login.html', {'unique_no': 'mobile number already exist.'})
        if int(len(password)) < 7:
            context.update({'error': 'Password must continent at-least 8 character.'})
            return render(request, 'InstructorDashboard/auth/login.html', context)

        if not (password == conf_password):
            context.update({'error': 'Password must be equal.'})
            return render(request, 'InstructorDashboard/auth/login.html', context)
        slug = generate_slug(first_name, last_name)
        user = user_models.User.objects.create(email=email, first_name=first_name, last_name=last_name,
                                               password=make_password(password), mobile_no=mobile_no,
                                               user_type=user_constants.Instructor)

        user_name = user.get_full_name()
        subject = "Registration Successful - Swim Time Solutions"
        email_body = f"Hello {user_name},\n \nWelcome to Swim Time Solutions, " \
                     f"Your account is now set up and ready to use. Let's get started!\n\n" \
                     f"Thank You," \
                     f"\nSwim Time Solutions"
        try:
            # sent_mail_task.apply_async(kwargs={'subject': subject, 'email_body': email_body,
            #                                    'user_email': email})
            mail_notification(request, subject, email_body, email)
        except Exception as e:
            pass

        logger.info(f"{user} created successfully.")
        front_end_url_local = os.environ.get("FRONT_END_URL_LOCAL")
        front_end_url = os.environ.get("FRONT_END_URL")
        if user:
            date_time = datetime.now()
            time_added = date_time + timedelta(minutes=1)
            user_profile = user_models.Profile.objects.create(
                user=user,
                slug=slug,
                url=(BASE_URL + '/swim/instructor/' + slug).replace(' ', ''),
                day_start_time=date_time.time(),
                day_end_time=time_added.time()
            )
            logger.info(f"{user_profile} profile successfully.")
            auth_user = authenticate(email=user.email, password=password)
            if auth_user:
                logger.info(f"{auth_user} is authorized successfully.")
                login(request, auth_user)
                logger.info(f"{auth_user} login successfully.")
                # return render(request, 'InstructorDashboard/instructor_profile.html', {'instructor': user_profile})
                return redirect('InstructorDashboard:instructor_profile')
        logger.info(f"{user.email} is not authorized with this credential.")
        return render(request, 'InstructorDashboard/auth/login.html')


def login_view(request):
    if request.user.is_authenticated:
        return redirect('InstructorDashboard:dashboard_view')

    context = {}
    if request.method == 'GET':
        return render(request, 'InstructorDashboard/auth/login.html')

    else:
        ser = serializer.LoginDataVerifier(data=request.POST)
        if not ser.is_valid():
            context.update({'errors': utility.serializer_error_to_dict(ser.errors)})
            return render(request, 'InstructorDashboard/auth/login.html', context=context)
        else:
            user = ser.get_user()
            if not user:
                context.update({'page_errors': ['Username or Password is incorrect.']})
                return render(request, 'InstructorDashboard/auth/login.html', context=context)
            if user.user_type == user_constants.Instructor:
                login(request, user)

                return redirect('InstructorDashboard:dashboard_view')
            context.update({'page_errors': ['User does not have permission to access this portal.']})
            return render(request, 'InstructorDashboard/auth/login.html', context=context)


def user_logout(request):
    logger.info(f"{request.user} Successfully Logged out")
    logout(request)
    return redirect('InstructorDashboard:home')


def home_view(request):
    return render(request, "index.html")


def increase(inst_count_id):
    inst_count_id += 1


def setzero(inst_count_id):
    inst_count_id = 0


@login_required(redirect_field_name='login')
def dashboard_view(request):
    if not request.user.user_type == user_constants.Instructor:
        return redirect('InstructorDashboard:user_logout')

    context = {}
    credit_amount = 0
    pending_amount = 0
    bookings = utilities.get_instructors_bookings(request.user)
    student_count = Kids.objects.filter(parent__inst_id=request.user.id)
    transactions = utilities.get_instructor_transactions(request.user)
    complete_transactions = utilities.get_complete_transactions(request.user)
    pending_transactions = utilities.get_pending_transactions(request.user)
    for complete_transaction in complete_transactions:
        credit_amount += complete_transaction.paid_amount
    for pending_transaction in pending_transactions:
        pending_amount += pending_transaction.paid_amount

    appointments = appointment_model.Appointment.objects.filter(booking__class_instructor__instructor=request.user,
                                                                status='1').order_by('start_time')
    for i in appointments:
        print(i.start_time)
    context = {'appointments': appointments,
               'transactions': transactions,
               'total_bookings': bookings.count(),
               'total_students': len(set([student.id for student in student_count])),
               'credit_amount': credit_amount,
               'pending_transaction': pending_amount
               }
    return render(request, 'InstructorDashboard/dashboard.html', context=context)


@login_required(redirect_field_name='login')
def trainee_view(request, trainee):
    try:
        trainee = user_models.Kids.objects.get(id=trainee)
    except user_models.Kids.DoesNotExist:
        return redirect('InstructorDashboard:page404')
    transactions = appointment_model.Transaction.objects.filter(booking__kids=trainee).order_by('-payment_at')
    today = datetime.today().replace(tzinfo=pytz.UTC)
    bookings = appointment_model.Booking.objects.filter(kids=trainee).order_by("-booked_at")
    appointment_status_options = dict(APPOINTMENT_STATUS)

    context = {'trainee': trainee,
               'transactions': transactions, 'bookings': bookings,
               'today': today, 'appointment_status_options': appointment_status_options}
    return render(request, 'InstructorDashboard/profile.html', context=context)


@login_required(redirect_field_name='login')
def cash_transactions(request):
    transactions = appointment_model.Transaction.objects.filter(
        booking__class_instructor__instructor_id=request.user.id, status='1').order_by('-payment_at')
    bookings = appointment_model.Booking.objects.filter(class_instructor__instructor_id=request.user.id).order_by(
        "-booked_at")
    name = request.user.first_name
    context = {'transactions': transactions, 'name': name, 'bookings': bookings}
    return render(request, 'InstructorDashboard/cash-transactions.html', context=context)

templates/InstructorDashboard/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>{% block title_block %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="SwimTime Swim Instructor Dashboard" name="description"/>
    <meta content="" name="author"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

    <!-- App favicon -->
    <link rel="shortcut icon" href="/static/images/favicon.ico">

    {% block exttra_style %}{% endblock %}
    <!-- App css -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/metisMenu.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css"/>
    <style>
        #preloader{
                position: fixed;
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                background-color: #fff;
                z-index: 99;
        }
        #status {
          width: 200px;
          height: 200px;
          position: absolute;
          left: 50%;
          top: 50%;
          background-image: url(https://raw.githubusercontent.com/niklausgerber/PreLoadMe/master/img/status.gif);
          background-repeat: no-repeat;
          background-position: center;
          margin: -100px 0 0 -100px;
}
        .top_alert_position {
            position: fixed;
            top: 2%;
            right: 10px;
            z-index: 9;
            width: auto;
            background: #fff;
            padding: 20px 10px !important;
        }

        .alert .alert-close {
            display: initial !important;
        }

        .profile_error {
            color: red;
        }
    </style>
</head>
<body>
<div id="preloader">
  <div id="status">&nbsp;</div>
</div>
<div class="left-sidenav">
    <!-- LOGO -->
    <div class="brand">
        <a href="{% url 'InstructorDashboard:dashboard_view' %}" class="logo" style="cursor: default">
            <h3>Swim Time Instructor</h3>
        </a>
    </div>
    <!--end logo-->
    <div class="menu-content h-100" data-simplebar>
        <ul class="metismenu left-sidenav-menu">
            <li>
                <a href="{% url 'InstructorDashboard:dashboard_view' %}">
                    <i data-feather="home" class="align-self-center menu-icon"></i>
                    <span class="menu-icon">Dashboard</span>
                </a>
            </li>
            <hr>
            <li>
                <a href="{% url 'InstructorDashboard:students' %}">
                    <i data-feather="users" class="align-self-center menu-icon"></i>
                    <span class="menu-icon">Students</span>
                </a>
            </li>
            <hr>
            <li>
                <a href="{% url 'InstructorDashboard:class_list' %}">
                    <i data-feather="calendar" class="align-self-center menu-icon"></i>
                    <span class="menu-icon">Classes</span>
                </a>
            </li>
            <hr>
            <li>
                <a href="{% url 'InstructorDashboard:booking_view' %}">
                    <i data-feather="book-open" class="align-self-center menu-icon"></i>
                    <span class="menu-icon">Bookings</span>
                </a>
            </li>
            <hr>
            <li>
                <a href="{% url 'InstructorDashboard:appointment_view' %}">
                    <i data-feather="file-text" class="align-self-center menu-icon"></i>
                    <span class="menu-icon">Appointments</span>
                </a>
            </li>
            <hr>
            <li>
                <a href="{% url 'InstructorDashboard:cash_transactions' %}">
                    <i data-feather="dollar-sign" class="align-self-center menu-icon"></i>
                    <span class="menu-icon" style="white-space: nowrap">Pending Cash</span>
                </a>
            </li>
        </ul>
    </div>
</div>

<div class="page-wrapper">
    <div class="topbar">
        <nav class="navbar-custom">
            <ul class="list-unstyled topbar-nav float-right mb-0">
                <li class="dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-toggle="dropdown"
                       href="#" role="button"
                       aria-haspopup="false" aria-expanded="false">
                        <span class="ml-1 nav-user-name hidden-sm">Welcome {{ request.user.get_full_name }}&nbsp;&nbsp;&nbsp;</span>
                        <img src="{{ user.profile_img.url }}" alt="profile-user" class="rounded-circle thumb-xs"/>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{% url 'InstructorDashboard:instructor_profile' %}">
                            <i data-feather="user" class="align-self-center icon-xs icon-dual mr-1"></i>
                            Profile
                        </a>
                        <div class="dropdown-divider mb-0"></div>
                        <a class="dropdown-item" href="{% url 'InstructorDashboard:user_logout' %}"><i
                                data-feather="power"
                                class="align-self-center icon-xs icon-dual mr-1"></i>
                            Logout</a>
                    </div>
                </li>
            </ul><!--end topbar-nav-->

            <ul class="list-unstyled topbar-nav mb-0">
                <li>
                    <button class="nav-link button-menu-mobile">
                        <i data-feather="menu" class="align-self-center topbar-icon"></i>
                    </button>
                </li>
            </ul>
        </nav>
        <!-- end navbar-->
    </div>
    {% block page_content %}
    {% endblock %}
    <footer class="footer text-center text-sm-left">
        {#        &copy; 2021 SwimTime <span class="d-none d-sm-inline-block float-right">Crafted with <i#}
        {#            class="mdi mdi-heart text-danger"></i> by Mannatthemes</span>#}
    </footer><!--end footer-->
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/metismenu.min.js' %}"></script>
<script src="{% static 'js/waves.js' %}"></script>
<script src="{% static 'js/feather.min.js' %}"></script>
<script src="{% static 'js/simplebar.min.js' %}"></script>
<script src="{% static 'js/moment.js' %}"></script>

{% block extra_script %}{% endblock %}
{#<script src="{% static 'pages/jquery.datatable.init.js' %}"></script>#}
<script src="{% static 'js/app.js' %}"></script>

<script>
    $(window).on('load', function() {
      $('#status').fadeOut();
      $('#preloader').delay(350).fadeOut('slow');
      $('body').delay(350).css({'overflow':'visible'});
    })
</script>


</body>